### PR TITLE
Add indent file

### PR DESCRIPTION
**Pull request by euclidianAce**
- [x] Adapt lua indent file
- [x] Indentation Options
- [x] Operators that start or end lines should indent
    - same for table/method accesses
```lua
local a = "foo" ..
    "bar"
local b = "foo"
    .. "bar"
object:create()
    :setOptionA()
    :setOptionB()
```
- [-] Dangling type annotations could maybe be indented, like
```
local function foo()
        : string
    return "baz"
end
```
(This isn't a huge priority)

I'll leave this up as a draft until I use it for a bit.
As well as tinker with it and work out any bugs.

Use the following to test this branch with vim plug
```
Plug 'teal-language/vim-teal', { 'branch': 'indent' }
```
(or just manually checkout and pull the branch down if you're lazy like me)

### CODE REVIEW

**Comment by 3uclidian** [comment]
One thing that the current file does that I'm personally not a fan of is that one line can cause the next to be indented multiple times, for example when a table is passed in as an argument to a function
(which I would indent as the following)
```lua
do
    table.concat({
        "foo",
        "bar"
    }, "\n")
end
```
the current script would indent something like this
```lua
do
    table.concat({
		"foo", -- indented twice
		"bar"
	    }, "\n")
end
```
Which is not my cup of tea, but I've seen people use similar formatting, so I think I'll add an option to choose which behavior is wanted.

**Comment by euclidianAce** [comment]
I'd say it's pretty feature complete now

**Comment by pdesaulniers** [comment]
As a test case, I tried indenting `tl.tl` with
```
gg
=G
```
...but it seems like it removed most of the indentation in the file. For instance, records declarations now look like this:
```lua
local Token = record
x: number
y: number
i: number
tk: string
kind: TokenKind
end

```

Is this normal? Am I missing something?

**Comment by euclidianAce** [comment]
Ah, looks like I broke something with the last few commits, hopefully its a quick fix

**Comment by euclidianAce** [comment]
Try it out now, hopefully it should work.

The issue was caused by an attempt to make trailing binary operators cause an indent.
After some consideration this minor thing doesn't seem worth it as it requires each line to look at the content of at least 2 lines above it.

**Comment by euclidianAce** [comment]
Wait, something else broke :P
I'll do some more thorough testing before my next commits

**Comment by euclidianAce** [comment]
*fingers crossed* One issue was caused by the syntax groups missing type annotations inside of tables. I just ran this commit on tl.tl and everything seems in order.
Let me know if you find anything else.

**Comment by pdesaulniers** [comment]
Ahhh, much better :) Excellent work so far!

I've found one function in tl.tl where the indentation looks a bit off:
```lua
local function parse_list<T>(ps: ParseState, i: number, list: {T}, close: {string:boolean}, sep: SeparatorMode, parse_item: ParseItem<T>): number, {T}
   local n = 1
   while ps.tokens[i].kind ~= "$EOF$" do
      if close[ps.tokens[i].tk] then
         (list as Node).yend = ps.tokens[i].y
      break
   end
   local item: T
   i, item, n = parse_item(ps, i, n)
   table.insert(list, item)
   if ps.tokens[i].tk == "," then
      i = i + 1
   elseif sep == "sep" and not close[ps.tokens[i].tk] then
      return fail(ps, i)
   elseif sep == "term" and ps.tokens[i].tk == ";" then
      i = i + 1
   end
end
return i, list
end
```

**Comment by pdesaulniers** [comment]
Maybe `teal_no_multi_indent` should be the default? It seems much more aesthetically pleasant to me as well.

**Comment by euclidianAce** [comment]
> Maybe `teal_no_multi_indent` should be the default? It seems much more aesthetically pleasant to me as well.

Sure.

The current issue I'm working with it that with large files vim starts to struggle with indentation. In particular, things inside of strings and type annotations are not being ignored. Presumably vim is sacrificing accuracy for speed at some point.

Are you getting the same results near the end of tl.tl where everything at the end is pushed off the screen? And is this the result of something in a recent commit?

**Comment by euclidianAce** [comment]
After some tinkering, it turns out the `searchpair` function gets insanely slow on large files. I'm going to try to use the default Lua indent file for some inspiration since it formatted tl.lua with `=G` in like a second, as opposed to the noticeable few seconds of freezing that the current one does to tl.tl

**Comment by pdesaulniers** [comment]
> Are you getting the same results near the end of tl.tl where everything at the end is pushed off the screen? And is this the result of something in a recent commit?

Yeah, many things are pushed to the left. It seems like 26a37e8 had similar issues.

> After some tinkering, it turns out the searchpair function gets insanely slow on large files

Personally, I think the indent script is fast enough. It seems comparable in speed with the default indent script for TypeScript. With that said, feel free to optimize it if you want to :stuck_out_tongue: 

> The current issue I'm working with it that with large files vim starts to struggle with indentation. In particular, things inside of strings and type annotations are not being ignored. Presumably vim is sacrificing accuracy for speed at some point.

Could this be an issue with the syntax file? Perhaps the tokens inside the string match the wrong syntax group? To debug this, maybe there's some way in Vim to check the syntax group at the cursor position?

**Comment by euclidianAce** [comment]
> maybe there's some way in Vim to check the syntax group at the cursor position?

Yeah, you can use some combination of `synID` and `synIDattr` to get syntax information at a given position, which is how the indent file currently attempts to skip over strings, comments, and type annotations. But directly from `:help synID`

> Warning: This function can be very slow.  Best speed is obtained by going through the file in forward direction.

And the current syntax file uses it multiple times per line whereas the original Lua one uses it like once. But I can't exactly pin it down as a direct reason of it failing.

The main issue is that it seems to be fine on smaller files, but bigger ones like tl.tl make it trip up. And the thing that makes me think that it's file size tripping it up is that you can work your way through tl.tl, hitting `=G` every couple hundred lines and the file will eventually indent correctly.

I'm doing some quick and dirty testing on some local branches that I have, so I honestly may scrap this branch eventually for a rewritten one that doesn't try to be as 'clever' (I guess) with its checking.

**Comment by euclidianAce** [comment]
I've rewritten this file a couple times and I think I've come to the conclusion that `=G` should just not be used on large files. At the very least the Lua syntax file that I based it on also had similar problems to this one with large files.

But in those rewrites, I've made a decently faster version (at least on my old machine) that should be easier to support certain syntaxes (tagged records comes to mind), so I think I'll just scrap this branch and open a new pull request so we don't have some random garbage commits on master.

**Pull request closed without merging**
